In [2]:
import pandas as pd #importa o pandas

EX.1: SALÁRIO SE

In [3]:
sal = pd.read_csv("Salaries.csv") #le o arquivo salaries.csv com df chamado sal

In [4]:
sal.head() #verifica o head do df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [5]:
sal.info() #usa o metodo .info() para ver entradas que tem

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), str(3)
memory usage: 14.7 MB

In [6]:
sal['BasePay'].mean()#basepay medio

np.float64(66325.44884048769)

In [7]:
sal['OvertimePay'].max()#maior qtd de overtimepay

np.float64(245131.88)

In [11]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'] #cargo de JOSEPH DRISCOLL (não joseph driscoll)

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [16]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL'] ['TotalPayBenefits']#quanto o JOSEPH ganha

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [20]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()] #pessoa mais bem paga

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [22]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]#pessoa menos paga, recebimento possui valor negativo, bug ou erro de escrita

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [26]:
sal.groupby('Year').mean(numeric_only=True)['BasePay']#media de todos os func por ano (11-14) / na versao do professor nao precisou de numeric_only, aqui
#não funcionava aí pesquisei e descobri que a versão antiga ignorava se a coluna nao tinha valores numericos

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [33]:
sal['JobTitle'].nunique() #quantos titulos unicos existem

2159

In [36]:
sal['JobTitle'].value_counts().head()#5 principais empregos mais comuns

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [37]:
sum(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1) #titulos de trabalho representados apenas por uma pessoa em 2013

202

In [38]:
def chefe_cargo(cargo):
    if 'chief' in cargo.lower():
        return True
    else:
        return False#pessoas que tem a palavra chefe em seu cargo

In [42]:
sum(sal['JobTitle'].apply(lambda x: chefe_cargo(x))) # lambda cria uma função anônima rápida para aplicar uma operação em cada elemento

627

In [44]:
sal['tam'] = sal['JobTitle'].apply(len) #existe relação entre o tamanho do titulo e total de ganhos?

In [46]:
sal[['tam', 'TotalPayBenefits']].corr() #correlaciona as duas colunas

                       tam  TotalPayBenefits
tam               1.000000         -0.036878
TotalPayBenefits -0.036878          1.000000

In [ ]:
#não existe relação